import express from 'express'
import * as memberController from '../controllers/memberController.js'
import {verifyAuthToken} from '../utilities/authentication.js'
import {isNewPasswordVlidate, isPasswordValidate} from '../validator/userValidation.js'

const router = express.Router()

router.post('/adduser', verifyAuthToken(), memberController.addHouseTalkUser)
router.post('/deleteuser', verifyAuthToken(), memberController.deleteHouseTalkUser)
router.post('/profile', verifyAuthToken(), memberController.memberProfile)
router.post('/edit', memberController.editMember)
router.post('/login', memberController.loginUser)
router.post('/updatemember', isPasswordValidate, verifyAuthToken(), memberController.updateMember)
router.post('/uploadbanner', verifyAuthToken(), memberController.manageMemberHomaPage)
router.post('/activebanner', verifyAuthToken(), memberController.activeHomePageBanner)
router.post('/editbanner', verifyAuthToken(), memberController.editBanner)
router.post('/gettemplatebanner', verifyAuthToken(), memberController.getAllHomePageBanner)
router.post('/getalltemplatebanner', memberController.getAllHomePageBanners)
router.post('/deletetemplatebanner', verifyAuthToken(), memberController.deleteHomePageBanner)
router.post('/addhousetalk', verifyAuthToken(), memberController.addHouseTalk)
router.post('/getallhousetalk', verifyAuthToken(), memberController.getAllHouseTalk)
router.post('/singlehousetalk', memberController.findSingleHouseTalk)
router.post('/updatehousetalk', verifyAuthToken(), memberController.editHouseTalk)
router.post('/onehousetalk', verifyAuthToken(), memberController.singleHouseTalk)
router.post('/deletehousetalk', verifyAuthToken(), memberController.deleteHouseTalk)
router.post('/getallusers', verifyAuthToken(), memberController.getAllUsers)
router.post('/getallagent', verifyAuthToken(), memberController.getChildUserData)
router.post('/addchilduser', verifyAuthToken(), memberController.addChildAgentUser)
router.post('/edituser', verifyAuthToken(), memberController.updateHouseTalkUser)
router.post('/updateuserstatus', verifyAuthToken(), memberController.updateUserStatus)
router.post('/updateemail', verifyAuthToken(), memberController.editEmailData)
router.post('/viewstats', memberController.viewStatisticsOfHoustalk)
router.post('/checkproperty', memberController.checkProperty)
router.post('/getviewstats', verifyAuthToken(), memberController.getAllStatsViews)
router.post('/propertyvisit', verifyAuthToken(), memberController.countAllVisitViews)
router.post('/sms', memberController.autoSmsReply)
router.post('/admindata', memberController.adminData)
router.post('/geofencing', memberController.geoFencing)
router.post('/tellafreind', memberController.tellAFreind)
router.post('/findpicturesarray', memberController.showImagesArray)
router.post('/uploadimagesinfolder', verifyAuthToken(), memberController.uploadAndUpdateImage)
router.post('/forgotpassword', memberController.forgotPassword)
router.post('/resetlink', memberController.resetPasswordLink)
router.post('/resetpassword', memberController.resetPassword)
router.post('/customerstat', memberController.getAllIncomingCustomerStat)
router.post('/customerisvisited', memberController.updateIncomingCustomerStat)
router.post("/findthreshold",verifyAuthToken(),memberController.radiusSearchOptions)
router.post("/sendpromotions",verifyAuthToken(),memberController.sendPromotionsToUser)
router.post("/getallagenthousetalk",verifyAuthToken(),memberController.getAllChildAgentHouseTalk)

export {router}
